version: '3'
services:
  app1:
    image: "node:18-alpine"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
      - PORT=5432
      - MESSAGE=Hello from first Express!
    ports:
      - 80:5432
    command: "npm start"

  app2:
    image: "node:18-alpine"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
      - PORT=1234
      - MESSAGE=This is my second Express app
    ports:
      - 8080:1234
    command: "npm start"

  app3:
    image: "node:18-alpine"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
      - PORT=2143
      - MESSAGE=And that is my last app
    ports:
      - 8081:2143
    command: "npm start"